#spring.datasource.url=jdbc:postgresql://10.0.2.15:5433/academiadb
spring.datasource.url=jdbc:postgresql://localhost:5433/academiadb
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true